In [1]:
import numpy as np

In [3]:
array1 = np.arange(6)

In [4]:
print(array1)

[0 1 2 3 4 5]


In [5]:
array1[3]

3

In [6]:
array1[1:4]

array([1, 2, 3])

In [7]:
array1[:4]

array([0, 1, 2, 3])

In [8]:
array1[2:]

array([2, 3, 4, 5])

In [10]:
array1[2:5] = 100

In [18]:
array2 = array1[2:5]

In [19]:
array2

array([100, 555, 100])

In [20]:
array2[1] = 555

In [21]:
array2[:] = 4444

In [22]:
array1

array([   0,    1, 4444, 4444, 4444,    5])

In [23]:
array_2d = np.arange(9)

In [24]:
array_2d.shape

(9,)

In [25]:
array_2d.ndim

1

In [28]:
array_2d_new = np.reshape(array_2d, (3, 3))

In [30]:
array_2d_new[1] = 5

In [35]:
array_2d_new.shape

(3, 3)

In [32]:
array_2d

array([0, 1, 2, 5, 5, 5, 6, 7, 8])

In [34]:
array_2d.shape

(9,)

In [36]:
array_2d_new

array([[0, 1, 2],
       [5, 5, 5],
       [6, 7, 8]])

In [44]:
array2_2d = array_2d.reshape(3, 3)

In [40]:
array2_2d[1] = 100 

In [41]:
array_2d

array([  0,   1,   2, 100, 100, 100,   6,   7,   8])

In [45]:
array_2d.resize((3, 3))

In [47]:
array_2d[1] = [3, 4, 5]

In [49]:
array_2d.shape

(3, 3)

In [50]:
array_2d.ndim

2

In [51]:
array_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
del array2_2d

In [53]:
del array_2d_new

In [59]:
print(array_2d[1])
print(array_2d[1][2])
print(array_2d[1, 2])

[3 4 5]
5
5


In [62]:
print(array_2d[1:3])
print(array_2d[1:3, 0:2])
print(array_2d[:, 0:2])

[[3 4 5]
 [6 7 8]]
[[3 4]
 [6 7]]
[[0 1]
 [3 4]
 [6 7]]


In [63]:
print(array_2d[:, 0:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [66]:
print(array_2d[:, 1])
print(array_2d[:, 1:2])
print(array_2d[:, 1:2].shape)

[1 4 7]
[[1]
 [4]
 [7]]
(3, 1)


In [72]:
print(array_2d)
print()
print(array_2d % 2 == 0)
print()
print(array_2d[array_2d % 2 == 0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ True False  True]
 [False  True False]
 [ True False  True]]

[0 2 4 6 8]


In [73]:
array_int = np.array([1, 0, 1])

In [75]:
mask = array_int == 1

In [76]:
mask

array([ True, False,  True])

In [77]:
array_2d[mask]

array([[0, 1, 2],
       [6, 7, 8]])

In [81]:
print(array_2d % 2 == 0)
print()
print(mask | (array_2d % 2 == 0))

[[ True False  True]
 [False  True False]
 [ True False  True]]

[[ True False  True]
 [ True  True  True]
 [ True False  True]]


In [83]:
print(array_2d)
print(array_2d[mask | (array_2d % 2 == 0)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 2 3 4 5 6 8]


In [86]:
print(array_2d)
print(array_2d[mask & (array_2d % 2 == 0)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [85]:
~mask

array([False,  True, False])

In [92]:
print(array_2d)
print()
print(array_2d.transpose())
print()
print(array_2d.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 3 6]
 [1 4 7]
 [2 5 8]]

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [97]:
print(array_2d)
array_2d.flatten().shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(9,)

In [100]:
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(3, 9).reshape(3, 2)
print(arr1)
print(arr2)

[[0 1 2]
 [3 4 5]]
[[3 4]
 [5 6]
 [7 8]]


In [102]:
print(np.dot(arr1, arr2))
print(arr1 @ arr2)

[[19 22]
 [64 76]]
[[19 22]
 [64 76]]


In [103]:
matrix1 = np.matrix([1, 2, 3])

In [105]:
print(matrix1 * matrix1.T)

[[14]]


In [110]:
print(array_2d)

print(array_2d.mean())

print(np.mean(array_2d))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4.0
4.0


In [112]:
print(array_2d.mean(axis=0))
print(np.mean(array_2d, axis=0))

[3. 4. 5.]
[3. 4. 5.]


In [113]:
print(array_2d.mean(axis=1))
print(np.mean(array_2d, axis=1))

[1. 4. 7.]
[1. 4. 7.]


In [116]:
print(array_2d.std())
print(array_2d.std(axis=0))
print(array_2d.std(axis=1))

2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [117]:
print(array_2d.sum())
print(array_2d.sum(axis=0))
print(array_2d.sum(axis=1))

36
[ 9 12 15]
[ 3 12 21]


In [2]:
import numpy as np

arr2d = np.array([[0, 1, 2], [3, 4, 5],[6, 7, 8]])

In [5]:
import numpy as np

arr2d = np.array([[0, 1, 2], [3, 4, 5],[6, 7, 8]])
names = np.array(["Steve", "Joe", "Steve"])

arr2d[(names == "Steve") | (arr2d % 2 == 0)]

array([0, 2, 3, 4, 5, 6, 8])