### NumPy array 與 Python 標準 list 的主要差異

#### 資料型態的統一性
- **NumPy array**：array 內的所有元素都必須是相同的資料型態，這樣能讓資料處理更有效率，但也限制了可儲存的資料型態多樣性。
- **list**：list 可以包含不同類型的資料，像是整數、字串和物件等。這樣提供了更多的彈性，但也可能使得資料操作的效率不及 NumPy array。

#### 效能表現
- **NumPy array**：因為資料型態的統一和底層的優化，NumPy array 在進行數學運算和向量化操作時特別優秀，尤其是在處理大量資料時。
- **list**：在處理大量資料和複雜的數學運算時，效能可能不如 NumPy array，特別是在需要進行大量元素層級運算的情況下。

#### 功能與方法
- **NumPy array**：支援許多專為資料分析和科學計算而優化的功能，比如矩陣運算、統計操作和向量化函式等。
- **list**：提供基本的資料操作功能，如新增、刪除、迭代等，但不支援複雜的數學運算和向量化操作。

#### 記憶體使用
- **NumPy array**：由於資料型態的統一和緊湊的儲存方式，NumPy array 儲存大型資料集時通常比 list 更節省記憶體。
- **list**：因為其靈活性，一個 list 可能會使用比 NumPy array 更多的記憶體，特別是當儲存大量元素的時候。

#### 使用場合
- **NumPy array**：常用於科學計算、資料分析、機器學習等領域，非常適合處理數字型資料。
- **list**：更常用於一般的資料儲存和處理，尤其是在資料類型多樣或大小變動較大的情況下。

總結來說，選擇使用 NumPy array 或是 list 取決於具體的應用需求。需要進行高效率的資料操作和計算時，NumPy array 是較佳的選擇。而對於資料型態多樣或大小不定的資料集，則可能更適合使用 list。

In [1]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])

In [4]:
print(arr1)

[1 2 3]


In [38]:
type(arr1[0])

numpy.int64

In [18]:
arr1 * 2

array([2, 4, 6])

In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


In [10]:
my_list = list(range(1000000))

In [14]:
%%time

for _ in range(10):
    my_list2 = []
    for i in my_list:
        my_list2.append(i * 2)

CPU times: user 366 ms, sys: 51.9 ms, total: 418 ms
Wall time: 418 ms


In [15]:
%%time

for _ in range(10):
    my_list2 = [i * 2 for i in my_list]

CPU times: user 199 ms, sys: 55.1 ms, total: 254 ms
Wall time: 253 ms


In [20]:
sum(my_list2)

999999000000

In [17]:
my_array = np.array(my_list)

In [19]:
%%time

for _ in range(10):
    my_array2 = my_array * 2

CPU times: user 13.6 ms, sys: 15.5 ms, total: 29.1 ms
Wall time: 36.6 ms


In [21]:
sum(my_array2)

999999000000

In [24]:
print(np.array([[1, 2], [3, 4]]))

[[1 2]
 [3 4]]


In [46]:
print(np.arange(2, 10))

[2 3 4 5 6 7 8 9]


In [27]:
list(range(2, 10, 2))

[2, 4, 6, 8]

In [47]:
np.linspace(0, 10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [49]:
np.linspace(0, 10, num=10, endpoint=False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [56]:
print(np.ones((2, 3), dtype=np.int64))

[[1 1 1]
 [1 1 1]]


In [60]:
array_zero = np.zeros((2, 3))

In [65]:
array_zero[0, 2] = 5

In [66]:
array_zero

array([[5., 0., 5.],
       [0., 0., 0.]])

In [74]:
np.empty((10, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [75]:
np.full((3, 4), 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
type(array1[0])

numpy.float64

In [44]:
print(np.array(["a", 3]))

['a' '3']
