In [1]:
import numpy as np

In [2]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [4]:
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(array1 + array1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [18]:
np.add(array1, array1)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
print(array1 - array1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
np.subtract(array1, array1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
print(array1 * array1)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
np.multiply(array1, array1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [9]:
print(array1 / array1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
np.divide(array1, array1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
print(array1 * 4)

[[ 4  8 12]
 [16 20 24]
 [28 32 36]]


In [23]:
np.multiply(array1, 4)

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [14]:
print(array1 ** 2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [25]:
np.square(array1)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
print(1 / array1)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


In [16]:
print(array1 > 5)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [17]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
array1.shape

(3, 3)

In [27]:
array1.ndim

2

In [28]:
array_1d = np.array([1, 2, 3])

In [29]:
array_1d.ndim

1

In [30]:
array_1d.shape

(3,)

In [31]:
array1.dtype

dtype('int64')

In [32]:
np.arange(10).dtype

dtype('int64')

In [33]:
np.linspace(1, 10).dtype

dtype('float64')

In [34]:
array1.size

9

In [35]:
array1.shape

(3, 3)