In [32]:
import numpy as np
import numpy.random as nr
# from numpy import random as nr

In [33]:
nr.seed(0)
nr.rand(3, 4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [31]:
np.random.seed(0)
np.random.randn(3, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [49]:
rng = nr.default_rng(seed=0)
rng.standard_normal((3, 4))

array([[ 0.12573022, -0.13210486,  0.64042265,  0.10490012],
       [-0.53566937,  0.36159505,  1.30400005,  0.94708096],
       [-0.70373524, -1.26542147, -0.62327446,  0.04132598]])

In [54]:
nr.seed(0)
nr.randint(2, 15, size=(3, 4))

array([[14,  7,  2,  5],
       [13,  5,  9, 11],
       [ 5,  7,  4,  6]])

In [59]:
nr.seed(0)
10 * nr.random((3, 4)) + 5

array([[10.48813504, 12.15189366, 11.02763376, 10.44883183],
       [ 9.23654799, 11.45894113,  9.37587211, 13.91773001],
       [14.63662761,  8.83441519, 12.91725038, 10.2889492 ]])