In [1]:
import numpy as np
import numpy.random as nr

In [5]:
nr.seed(0)
array1 = nr.randint(10, size=(2, 3))

In [6]:
print(array1)

[[5 0 3]
 [3 7 9]]


In [ ]:
np.split()

In [20]:
varr = np.vsplit(array1, [1])

In [24]:
print(type(varr))
print(varr)
print(varr[0].shape)

<class 'list'>
[array([[5, 0, 3]]), array([[3, 7, 9]])]
(1, 3)


In [28]:
harr = np.hsplit(array1, [1, 2])

In [29]:
harr

[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]

In [31]:
np.split(array1, [1], axis=1)

[array([[5],
        [3]]),
 array([[0, 3],
        [7, 9]])]

In [37]:
print(np.concatenate((varr[1], varr[0]), axis=0))
print(np.concatenate((varr[1], varr[0]), axis=1))

[[3 7 9]
 [5 0 3]]
[[3 7 9 5 0 3]]


In [39]:
np.vstack((varr[1], varr[0]))

array([[3, 7, 9],
       [5, 0, 3]])

In [41]:
array2 = np.hstack((varr[1], varr[0]))

In [42]:
print(array2)

[[3 7 9 5 0 3]]


In [44]:
np.sort(array1)

array([[0, 3, 5],
       [3, 7, 9]])

In [47]:
array3 = np.array([[1, 2, 3], [1, 3, 1]])

In [48]:
np.sort(array3)

array([[1, 2, 3],
       [1, 1, 3]])

In [66]:
arr2d = np.array([[12, 15, 7], [4, 6, 10], [9, 8, 3]])

In [67]:
print(arr2d)

[[12 15  7]
 [ 4  6 10]
 [ 9  8  3]]


In [68]:
np.sort(arr2d)

array([[ 7, 12, 15],
       [ 4,  6, 10],
       [ 3,  8,  9]])

In [72]:
args = np.argsort(arr2d)
print(args)

[[2 0 1]
 [0 1 2]
 [2 1 0]]


In [71]:
np.take_along_axis(arr2d, args, axis=1)

array([[ 7, 12, 15],
       [ 4,  6, 10],
       [ 3,  8,  9]])

In [73]:
array3 = np.array([3, 1, 2])

In [75]:
a = np.argsort(array3)

In [76]:
array3[a]

array([1, 2, 3])

In [78]:
array3[np.where(array3 > 1)]

array([3, 2])

In [79]:
np.where(array3 > 1)

(array([0, 2]),)